perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./.git/config
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./.git/logs/HEAD
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./.git/logs/refs/heads/master
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./.git/logs/refs/remotes/origin/HEAD
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./README.md
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./commontypes/types.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./go.mod
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./internal/configdigesthelper/convert.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./internal/loghelper/close_log_error.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./internal/loghelper/if_not_stopped.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./internal/loghelper/logger_with_context.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./networking/bootstrapper_v1.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./networking/bootstrapper_v1v2.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./networking/bootstrapper_v2.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./networking/connection_gater.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./networking/dht-router/acl.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./networking/dht-router/acl_routing_table_filters.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./networking/dht-router/aclhost.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./networking/dht-router/announcement.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./networking/dht-router/config.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./networking/dht-router/dht.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./networking/dht-router/router.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./networking/knockingtls/knocking_tls.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./networking/knockingtls/limiters.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./networking/knockingtls/rate_limited_conn.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./networking/ocr1_peer.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./networking/ocr2_peer.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./networking/ocr_endpoint_v1.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./networking/ocr_endpoint_v1v2.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./networking/ocr_endpoint_v2.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./networking/peer.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./networking/peer_v1.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./networking/peer_v2.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./networking/ragedisco/address.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./networking/ragedisco/announcement.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./networking/ragedisco/connectivity.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./networking/ragedisco/discovery_protocol.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./networking/ragedisco/group.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./networking/ragedisco/helpers.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./networking/ragedisco/ragep2p_discoverer.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting/bootstrap_node.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting/confighelper/confighelper.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting/internal/config/config_digest.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting/internal/config/encode.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting/internal/config/public_config.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting/internal/config/shared_config.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting/internal/config/shared_secret.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting/internal/config/shared_secret_encrypt_xxx.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting/internal/managed/collect_garbage.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting/internal/managed/config_overrider.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting/internal/managed/forward_telemetry.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting/internal/managed/load_from_database.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting/internal/managed/managed_bootstrap_node.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting/internal/managed/managed_oracle.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting/internal/managed/track_config.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting/internal/protocol/attested_report.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting/internal/protocol/heap.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting/internal/protocol/message.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting/internal/protocol/network.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting/internal/protocol/observation.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting/internal/protocol/observation/observation.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting/internal/protocol/oracle.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting/internal/protocol/pacemaker.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting/internal/protocol/persist/persist.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting/internal/protocol/report_context.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting/internal/protocol/report_generation.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting/internal/protocol/report_generation_follower.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting/internal/protocol/report_generation_leader.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting/internal/protocol/telemetry.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting/internal/protocol/test_helpers.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting/internal/protocol/transmission.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting/internal/serialization/serialization.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting/internal/shim/endpoint.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting/internal/shim/telemetry_sender.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting/internal/signature/on_chain_signature.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting/oracle.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting/types/types.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting/validate_local_config.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2/chains/evmutil/alias.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2/confighelper/alias.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2/reportingplugin/median/evmreportcodec/reportcodec.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2/reportingplugin/median/median.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2/reportingplugin/median/value.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2/reportingplugin/titlerequest/titlerequest.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2/types/alias.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/bootstrapper.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/chains/evmutil/config_digest.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/chains/evmutil/evm.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/chains/evmutil/offchain_config_digester.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/confighelper/confighelper.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/config/netconfig/netconfig.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/config/ocr2config/public_config.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/config/ocr2config/serialize.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/config/ocr2config/shared_config.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/config/ocr3config/public_config.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/config/ocr3config/serialize.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/config/ocr3config/shared_config.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/config/oracle_identity.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/config/shared_secret.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/config/shared_secret_encrypt_xxx.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/managed/collect_garbage.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/managed/config_digest.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/managed/forward_telemetry.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/managed/limits.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/managed/load_from_database.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/managed/managed_bootstrapper.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/managed/managed_mercury_oracle.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/managed/managed_ocr2_oracle.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/managed/run_with_contract_config.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/managed/track_config.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/mercuryshim/mercuryshims.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/ocr2/protocol/attested_report.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/ocr2/protocol/heap.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/ocr2/protocol/message.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/ocr2/protocol/network.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/ocr2/protocol/observation.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/ocr2/protocol/oracle.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/ocr2/protocol/pacemaker.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/ocr2/protocol/persist/persist_pacemaker.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/ocr2/protocol/persist/persist_transmission.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/ocr2/protocol/report_finalization.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/ocr2/protocol/report_generation.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/ocr2/protocol/report_generation_follower.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/ocr2/protocol/report_generation_leader.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/ocr2/protocol/telemetry.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/ocr2/protocol/test_helpers.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/ocr2/protocol/transmission.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/ocr2/serialization/serialization.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/ocr3/protocol/attested_report.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/ocr3/protocol/common.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/ocr3/protocol/db.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/ocr3/protocol/message.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/ocr3/protocol/network.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/ocr3/protocol/oracle.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/ocr3/protocol/pacemaker.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/ocr3/protocol/persist/persist_transmission.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/ocr3/protocol/pool/pool.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/ocr3/protocol/report_finalization.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/ocr3/protocol/report_generation.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/ocr3/protocol/report_generation_follower.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/ocr3/protocol/report_generation_leader.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/ocr3/protocol/signed_data.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/ocr3/protocol/telemetry.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/ocr3/protocol/test_helpers.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/ocr3/protocol/transmission.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/ocr3/scheduler/scheduler.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/ocr3/serialization/serialization.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/shim/ocr2_serializing_endpoint.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/shim/ocr2_telemetry_sender.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/shim/ocr3_database.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/shim/ocr3_serializing_endpoint.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/shim/ocr3_telemetry_sender.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/internal/shim/reporting_plugin.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/ocr3types/counting_mercury_plugin.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/ocr3types/db.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/ocr3types/mercury_plugin.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/ocr3types/plugin.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/ocr3types/types.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/oracle.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/types/types.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./offchainreporting2plus/validate_local_config.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./ragep2p/conn_rate_limiter.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./ragep2p/demuxer.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./ragep2p/frame.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./ragep2p/internal/knock/knock.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./ragep2p/internal/ratelimitedconn/rate_limited_conn.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./ragep2p/loggers/logrus.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./ragep2p/ragep2p.go
perl -i -p -e "s/Goplugin\/PluginV2Lib/GoPlugin\/pluginV2Lib/g" ./ragep2p/types/types.go
