perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./.git/config
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./.git/logs/HEAD
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./.git/logs/refs/heads/master
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./.git/logs/refs/remotes/origin/HEAD
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./TUTORIAL.md
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./chaos/experiments.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./client/chaos.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./e2e/local-runner/envs_test.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./e2e/remote-runner/remote_runner_envs_test.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./environment/artifacts.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./environment/environment.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./environment/runner.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./examples/clones/clones.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./examples/concurrent/env_test.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./examples/coverage/env.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./examples/deployment_part/cmd/env.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./examples/deployment_part/sol.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./examples/deployment_part_cdk8s/blockscout.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./examples/deployment_part_cdk8s/cmd/env.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./examples/dump/env.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./examples/modify_cdk8s/env.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./examples/modify_helm/env.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./examples/multistage/env.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./examples/quick-debug/env.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./examples/remote-test-runner/env.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./examples/resources/env.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./examples/simple/env.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./go.mod
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./imports/k8s/httpchaos/chaosmeshorg/chaosmeshorg.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./imports/k8s/iochaos/chaosmeshorg/chaosmeshorg.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./imports/k8s/k8s.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./imports/k8s/networkchaos/chaosmeshorg/chaosmeshorg.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./imports/k8s/podchaos/chaosmeshorg/chaosmeshorg.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./imports/k8s/podiochaos/chaosmeshorg/chaosmeshorg.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./imports/k8s/podnetworkchaos/chaosmeshorg/chaosmeshorg.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./imports/k8s/stresschaos/chaosmeshorg/chaosmeshorg.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./imports/k8s/timechaos/chaosmeshorg/chaosmeshorg.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./logging/log.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./pkg/alias/alias.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./pkg/cdk8s/blockscout/blockscout.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./pkg/cdk8s/goc/goc.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./pkg/cdk8s/http_dummy/dummy.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./pkg/common.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./pkg/helm/chainlink/chainlink.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./pkg/helm/ethereum/geth.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./pkg/helm/grafana/grafana.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./pkg/helm/influxdb/influxdb.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./pkg/helm/kafka-rest/kafka-rest.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./pkg/helm/kafka/kafka.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./pkg/helm/mockserver-cfg/mockserver-cfg.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./pkg/helm/mockserver/mockserver.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./pkg/helm/polygon-edge/edge.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./pkg/helm/reorg/reorg.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./pkg/helm/schema-registry/schema-registry.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./pkg/helm/sol/sol.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./pkg/helm/starknet/starknet.go
perl -i -p -e "s/smartcontractkit\/chainlink/GoPlugin\/pluginV2Lib\/pluginV2/g" ./presets/presets.go
